services:
  django:
    container_name: django
    build:
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/src/
    command: ["uv", "run", "manage.py", "runserver", "0.0.0.0:8080"]

  tasks:
    container_name: tasks
    build:
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./src/:/src/
    command: ["uv", "run", "manage.py", "db_worker"]
    
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: